labels: &labels
  - name: "t: bug"
    color: "B60205"
    description: "A bug that needs to be fixed"
  - name: "t: feature"
    color: "B60205"
    description: "A feature to be implemented"
  - name: "t: chore"
    color: "B60205"
    description: "A change that doesn't affect the codebase"
  - name: "t: docs"
    color: "B60205"
    description: "A change that updates the documentation"
  - name: "s: abandoned"
    color: "5319E7"
    description: "A feature that has been abandoned"
  - name: "s: approved"
    color: "5319E7"
    description: "A feature that has been approved"
  - name: "s: rejected"
    color: "5319E7"
    description: "A feature that has been rejected"
  - name: "s: merged"
    color: "5319E7"
    description: "A feature that has been merged"
  - name: "s: wont fix"
    color: "5319E7"
    description: "A bug that won't be fixed"
  - name: "s: in progress"
    color: "5319E7"
    description: "A feature that is in progress"
  - name: "s: awaiting approval"
    color: "5319E7"
    description: "A feature that is awaiting approval"
  - name: "s: needs review"
    color: "5319E7"
    description: "A feature that needs review"

repositories:
  - owner: vcokltfre
    name: labelsync
    labels: *labels
